# Generated by Django 3.2 on 2021-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
